## makeCacheMatrix and cacheSolve, used jointly, can calculate, store and retrieve
## a cached value for an inverse of a matrix.  This can be used to avoid
## unnecessarily repeating a potentially computationally intensive task.

## makeCacheMatrix takes a matrix, x, and creates a new object
## that includes this matrix as well as a list of functions that
## can be used to calculate the inverse, cache it, and retrieve
## the cached value.

makeCacheMatrix <- function(x = matrix()) {

  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m
  list(set = set, get = get,
        setinverse = setinverse,
        getinverse = getinverse)
}


## cacheSolve takes an object, x, including a matrix and 
## the list of functions generated by makeCacheMatrix, and
## returns the cached inverse if it already exists.  If not, it
## calculates, returns, and caches the inverse.

cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}